### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by hsblhsn** [hsblhsn/microstate#2]
- [ ] Add support for `microstate clean` command.
- [ ] Add support for `microstate rollback ...` command.
- [ ] Add support for digest and block based versioning.
